apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      imagePullSecrets:
        - name: ecr-login
      containers:
        - name: register-app
          image: 231791477922.dkr.ecr.ap-northeast-1.amazonaws.com/register-app-pipeline:1.0.0-21
          imagePullPolicy: Always
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
